import Link from "next/link";
import Image from "next/image";
import { ArrowDownRight, ArrowUpRight, Mail } from "lucide-react";
import { projects } from "@/data/projects";
import { technologies, socials } from "@/data/site";
import { ProjectCard } from "@/components/project-card";
import { SectionHeading } from "@/components/section-heading";

export default function Home() {
  return <main id="conteudo">
    <section className="hero" id="inicio"><div className="container hero-inner">
      <div className="hero-copy"><p className="kicker"><span /> Desenvolvimento & produto digital</p><h1>Ideias que viram<br/><em>produtos.</em></h1><p className="hero-text">Desenvolvendo projetos digitais que transformam ideias em soluções reais.</p><div className="hero-actions"><Link href="/projetos" className="button primary">Ver projetos <ArrowDownRight size={18} /></Link><a href="https://github.com/chrstack" target="_blank" rel="noreferrer" className="button secondary">GitHub <ArrowUpRight size={18} /></a></div></div>
      <div className="hero-mark" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><Image src="/brand/symbol.png" alt="" width={250} height={250} priority /><span className="coordinate c1">09°40&apos;S</span><span className="coordinate c2">35°44&apos;W</span></div>
      <div className="scroll-hint"><span>Explore</span><i /></div>
    </div></section>
    <section className="section projects-section" id="projetos"><div className="container"><SectionHeading number="01" title="Projetos em destaque" intro="Produtos próprios e cases técnicos construídos a partir de problemas reais."/><div className="project-grid">{projects.map((project) => <ProjectCard key={project.slug} project={project} />)}</div><Link href="/projetos" className="all-projects">Ver todos os projetos <ArrowUpRight size={18}/></Link></div></section>
    <section className="section about-section" id="sobre"><div className="container about-grid"><SectionHeading number="02" title="Sobre"/><div className="about-copy"><p className="lead">Sou Christian Lima, desenvolvedor e criador do <strong>chrstack<span className="dot">.</span></strong></p><p>Minha trajetória em tecnologia acontece principalmente pela prática: parto de um problema, organizo a ideia como produto e trabalho até transformá-la em uma experiência funcional.</p><p>Gosto de construir interfaces claras, pensar no caminho completo de quem usa e entender como cada decisão técnica melhora — ou complica — a solução. É assim que projetos como Currículo Pronto e SETTZ evoluem.</p><p>O chrstack é a identidade sob a qual reúno esse trabalho: produtos próprios, aprendizado aplicado e melhoria contínua, da primeira hipótese ao deploy.</p><div className="about-pillars"><div><span>01</span><strong>Produto</strong><p>Problemas reais antes de funcionalidades.</p></div><div><span>02</span><strong>Desenvolvimento</strong><p>Web responsiva, acessível e sustentável.</p></div><div><span>03</span><strong>Evolução</strong><p>Testar, aprender e refinar com clareza.</p></div></div><div className="about-line"><span>Christian Lima</span><i/><span>Maceió, AL · Brasil</span></div></div></div></section>
    <section className="section stack-section" id="stack"><div className="container"><SectionHeading number="03" title="Tecnologias" intro="Ferramentas que utilizo nos projetos."/><div className="stack-list">{technologies.map((tech, index) => <div key={tech}><span>{String(index + 1).padStart(2,"0")}</span><strong>{tech}</strong><i>↗</i></div>)}</div></div></section>
    <section className="section contact-section" id="contato"><div className="container contact-card"><p className="kicker"><span/> Disponível para novas conexões</p><h2>Vamos construir<br/>algo <em>relevante?</em></h2><p>Tem uma ideia, projeto ou quer trocar uma ideia sobre tecnologia? Escreva diretamente ou me encontre nas redes.</p><div className="contact-email-wrap"><a className="button primary" href="mailto:chrstack.dev@gmail.com"><Mail size={18}/> Enviar e-mail</a><span className="contact-address">chrstack.dev@gmail.com</span></div><div className="contact-links">{socials.slice(1,4).map((social) => <a key={social.label} href={social.href} target="_blank" rel="noreferrer">{social.label}<ArrowUpRight size={18}/></a>)}</div></div></section>
  </main>;
}
