import Link from "next/link";
import Image from "next/image";
import { ArrowDownRight, ArrowUpRight, Mail } from "lucide-react";
import { featuredProjects } from "@/data/projects";
import { articles } from "@/data/articles";
import { technologies, socials } from "@/data/site";
import { ProjectCard } from "@/components/project-card";
import { SectionHeading } from "@/components/section-heading";
import { ContactForm } from "@/components/contact-form";

export default function Home() {
  return <main id="conteudo">
    <section className="hero" id="inicio"><div className="container hero-inner">
      <div className="hero-copy"><p className="kicker"><span /> Christian Lima · Desenvolvedor</p><h1>Ideias que viram<br/><em>produtos.</em></h1><p className="hero-text">Produtos digitais, automações e experiências web construídos do problema ao deploy.</p><div className="hero-actions"><Link href="/projetos" className="button primary">Explorar projetos <ArrowDownRight size={18} /></Link><a href="https://github.com/chrstack" target="_blank" rel="noreferrer" className="button secondary">GitHub <ArrowUpRight size={18} /></a></div><div className="hero-proof"><span>Produto</span><span>Desenvolvimento</span><span>Dados</span></div></div>
      <div className="hero-mark" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><Image src="/brand/symbol.png" alt="" width={250} height={250} priority /></div>
      <div className="scroll-hint"><span>Explore</span><i /></div>
    </div></section>
    <section className="section projects-section" id="projetos"><div className="container"><SectionHeading number="01" title="Projetos em destaque" intro="Produtos próprios e cases técnicos construídos a partir de problemas reais."/><div className="project-grid featured-project-grid">{featuredProjects.map((project) => <ProjectCard key={project.slug} project={project} />)}</div><Link href="/projetos" className="all-projects">Ver todos os projetos <ArrowUpRight size={18}/></Link></div></section>
    <section className="section about-section" id="sobre"><div className="container about-grid"><SectionHeading number="02" title="Sobre"/><div className="about-copy"><p className="lead">Sou Christian Lima, desenvolvedor e criador do <strong>chrstack<span className="dot">.</span></strong></p><p>Minha trajetória em tecnologia acontece principalmente pela prática: parto de um problema, organizo a ideia como produto e trabalho até transformá-la em uma experiência funcional.</p><p>Gosto de construir interfaces claras, pensar no caminho completo de quem usa e entender como cada decisão técnica melhora — ou complica — a solução. É assim que projetos como Currículo Pronto e SETTZ evoluem.</p><p>O chrstack é a identidade sob a qual reúno esse trabalho: produtos próprios, aprendizado aplicado e melhoria contínua, da primeira hipótese ao deploy.</p><div className="about-pillars"><div><span>01</span><strong>Produto</strong><p>Problemas reais antes de funcionalidades.</p></div><div><span>02</span><strong>Desenvolvimento</strong><p>Web responsiva, acessível e sustentável.</p></div><div><span>03</span><strong>Evolução</strong><p>Testar, aprender e refinar com clareza.</p></div></div><div className="about-line"><span>Christian Lima</span><i/><span>Maceió, AL · Brasil</span></div></div></div></section>
    <section className="section experience-section" id="experiencia"><div className="container"><SectionHeading number="03" title="Experiência aplicada" intro="Tecnologia usada em produtos próprios e problemas reais de trabalho."/><div className="experience-list"><article><span>01</span><div><p className="eyebrow">Experiência profissional · Case anonimizado</p><h3>Automação de processos operacionais</h3><p>Desenvolvimento de automação com Python, Playwright e comparação aproximada de textos para reduzir etapas repetitivas de pesquisa e conferência, preservando validação humana e dados sensíveis.</p></div></article><article><span>02</span><div><p className="eyebrow">Dados · Case anonimizado</p><h3>Conferência e análise de bases</h3><p>Tratamento, cruzamento e validação de dados para identificar duplicidades, divergências e registros ausentes, com organização dos resultados em planilhas e visualizações.</p></div></article><article><span>03</span><div><p className="eyebrow">Produtos próprios · Desenvolvimento contínuo</p><h3>Construção de produtos digitais</h3><p>Planejamento, desenvolvimento e publicação de aplicações web, conectando decisões de produto, interface responsiva, código, GitHub e deploy na Vercel.</p></div></article></div></div></section>
    <section className="section stack-section" id="stack"><div className="container"><SectionHeading number="04" title="Tecnologias" intro="Ferramentas que utilizo nos projetos."/><div className="stack-list">{technologies.map((tech, index) => <div key={tech}><span>{String(index + 1).padStart(2,"0")}</span><strong>{tech}</strong><i>↗</i></div>)}</div></div></section>
    <section className="section articles-section" id="artigos"><div className="container"><SectionHeading number="05" title="Notas técnicas" intro="Processo, decisões e aprendizados além do código."/><div className="home-articles">{articles.map((article) => <Link key={article.slug} href={`/artigos/${article.slug}`}><p className="eyebrow">{article.category}</p><h3>{article.title}</h3><p>{article.description}</p><span>Ler artigo <ArrowUpRight size={16}/></span></Link>)}</div><Link className="all-projects" href="/artigos">Ver todos os artigos <ArrowUpRight size={18}/></Link></div></section>
    <section className="section contact-section" id="contato"><div className="container contact-card"><div className="contact-layout"><div><p className="kicker"><span/> Disponível para novas conexões</p><h2>Vamos construir<br/>algo <em>relevante?</em></h2><p>Tem uma ideia, projeto ou quer trocar uma ideia sobre tecnologia? Escreva diretamente ou me encontre nas redes.</p><a className="contact-email-card" href="mailto:chrstack.dev@gmail.com"><span className="contact-email-icon"><Mail size={20}/></span><span className="contact-email-copy"><small>Contato por e-mail</small><strong>chrstack.dev@gmail.com</strong></span><ArrowUpRight className="contact-email-arrow" size={20}/></a><div className="contact-links">{socials.slice(1).map((social) => <a key={social.label} href={social.href} target="_blank" rel="noreferrer">{social.label}<ArrowUpRight size={18}/></a>)}</div></div><ContactForm /></div></div></section>
  </main>;
}
